<!DOCTYPE html>
<html>
    <head>
        <title>ID 95 - 98SeaTurtles Network</title>
        <link rel="stylesheet" href="/css/main.css">
		<?php include $_SERVER['DOCUMENT_ROOT'] . "/include/head.php"; ?>
    </head>
    <body>
        <?php
			include $_SERVER['DOCUMENT_ROOT'] . "/include/header.html";
            include $_SERVER['DOCUMENT_ROOT'] . "/include/menu.html";
        ?>
        <div id="content">
            <a href=".."><i>Back to My Computers</i></a>
            <div id="content-title">
                ID 95
            </div>
            <div id="content-subtitle">
                VideoGame Server
            </div>
            <div id="content-body"><br>
                This server was built out of the parts of a friends old computer that he did not want anymore after he upgraded<br>
                
                <h3>Operating System</h3> Debian 9 Stretch<br>
                <h3>VideoGame Servers</h3>
                <list>
                    <li>Factorio (Planned)</li>
                    <li>FTB-Inifnity Minecraft Modpack</li>
                    <li>Le Modpack Minecraft Modpack by Anthony</li>
                    <li>Vanilla minecraft 1.12.2 for Skye</li>
                </list>
                
                <h3>Parts List</h3>
<a href="https://pcpartpicker.com/list/VyJCHN">PCPartPicker part list</a> / <a href="https://pcpartpicker.com/list/VyJCHN/by_merchant/">Price breakdown by merchant</a>
<table class="pcpp-part-list">
  <thead>
    <tr>
      <th>Type</th>
      <th>Item</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="pcpp-part-list-type">CPU</td>
      <td class="pcpp-part-list-item"><a href="https://pcpartpicker.com/product/Vjzv6h/intel-cpu-bx80637i73770">Intel - Core i7-3770 3.4GHz Quad-Core Processor</a></td>
      <td class="pcpp-part-list-price">
        Purchased For $0.00
      </td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">CPU Cooler</td>
      <td class="pcpp-part-list-item"><a href="https://pcpartpicker.com/product/LPVBD3/cryorig-cpu-cooler-m9i">CRYORIG - M9i 48.4 CFM CPU Cooler</a></td>
      <td class="pcpp-part-list-price">
        Purchased For $20.00
      </td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">Power Supply</td>
      <td class="pcpp-part-list-item"><a href="https://pcpartpicker.com/product/BfDzK8/corsair-vs-400w-80-certified-atx-power-supply-cp-9020117-na">Corsair - VS 400W 80+ Certified ATX Power Supply</a></td>
      <td class="pcpp-part-list-price">
        Purchased For $37.96
      </td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">Other</td>
      <td class="pcpp-part-list-item">Dell Studio XPS 8500 Motherboard DH77M01 NW73C YJPT1</td>
      <td class="pcpp-part-list-price">Purchased</td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">Other</td>
      <td class="pcpp-part-list-item">Hynix 4GB PC3-12800 DDR3- 1600MHz non-ECC Unbuffered CL11 240-Pin DIMM HMT351U6CFR8C-PB</td>
      <td class="pcpp-part-list-price">Purchased</td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">Other</td>
      <td class="pcpp-part-list-item">Rosewill 4U Server Chassis / Server Case / Rackmount Case, Metal Rack Mount Computer Case with 8 Bays & 4 Fans Pre-Installed (RSV-R4000)</td>
      <td class="pcpp-part-list-price">Purchased For $90.04</td>
    </tr>
    <tr>
      <td></td>
      <td class="pcpp-part-list-price-note">Prices include shipping, taxes, rebates, and discounts</td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td class="pcpp-part-list-total">Total</td>
      <td class="pcpp-part-list-total-price">$148.00</td>
    </tr>
    <tr>
      <td></td>
      <td class="pcpp-part-list-price-note">Generated by <a href="http://pcpartpicker.com">PCPartPicker</a> 2017-10-13 16:31 EDT-0400</td>
      <td></td>
    </tr>
  </tbody>
</table>
                
            </div>
        </div>
        <?php include $_SERVER['DOCUMENT_ROOT'] . "/include/footer.html";?>
    </body>
</html>