<!DOCTYPE html>
<html>
    <head>
        <title>ID 42 - 98SeaTurtles Network</title>
        <link rel="stylesheet" href="/css/main.css">
		<?php include $_SERVER['DOCUMENT_ROOT'] . "/include/head.php"; ?>
    </head>
    <body>
        <?php
			include $_SERVER['DOCUMENT_ROOT'] . "/include/header.html";
            include $_SERVER['DOCUMENT_ROOT'] . "/include/menu.html";
        include $_SERVER['DOCUMENT_ROOT'] . "/include/ad/large-right-collum.php";
        ?>
        <div id="content">
            <a href=".."><i>Back to My Computers</i></a>
            <div id="content-title">
                ID 42
            </div>
            <div id="content-body">
                Portable Gaming Rig<br>
                awesome little itx sfpc built in a node-202 case<br>
                <br>
                
<a href="https://pcpartpicker.com/list/NDmTWD">PCPartPicker part list</a> / <a href="https://pcpartpicker.com/list/NDmTWD/by_merchant/">Price breakdown by merchant</a>
<table class="pcpp-part-list">
  <thead>
    <tr>
      <th>Type</th>
      <th>Item</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="pcpp-part-list-type">CPU</td>
      <td class="pcpp-part-list-item"><a href="https://pcpartpicker.com/product/mV98TW/amd-ryzen-5-1600-32ghz-6-core-processor-yd1600bbaebox">AMD - Ryzen 5 1600 3.2GHz 6-Core Processor</a></td>
      <td class="pcpp-part-list-price">
        Purchased For $189.99
      </td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">CPU Cooler</td>
      <td class="pcpp-part-list-item"><a href="https://pcpartpicker.com/product/Lbhj4D/cryorig-cpu-cooler-c7">CRYORIG - C7 40.5 CFM CPU Cooler</a></td>
      <td class="pcpp-part-list-price">
        Purchased For $26.99
      </td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">Motherboard</td>
      <td class="pcpp-part-list-item"><a href="https://pcpartpicker.com/product/nG98TW/asrock-ab350-gaming-itxac-mini-itx-am4-motherboard-ab350-gaming-itxac">ASRock - AB350 Gaming-ITX/ac Mini ITX AM4 Motherboard</a></td>
      <td class="pcpp-part-list-price">
        Purchased For $94.99
      </td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">Memory</td>
      <td class="pcpp-part-list-item"><a href="https://pcpartpicker.com/product/RTJkcf/gskill-memory-f42666c15s8gvr">G.Skill - Ripjaws V Series 8GB (1 x 8GB) DDR4-2666 Memory</a></td>
      <td class="pcpp-part-list-price">
        Purchased For $69.99
      </td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">Storage</td>
      <td class="pcpp-part-list-item"><a href="https://pcpartpicker.com/product/RzfmP6/pny-internal-hard-drive-ssd7cs1311120rb">PNY - CS1311 120GB 2.5" Solid State Drive</a></td>
      <td class="pcpp-part-list-price">
        Purchased For $59.66
      </td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">Storage</td>
      <td class="pcpp-part-list-item"><a href="https://pcpartpicker.com/product/rTGkcf/hitachi-internal-hard-drive-0j22423">Hitachi - Travelstar 1TB 2.5" 7200RPM Internal Hard Drive</a></td>
      <td class="pcpp-part-list-price">
        Purchased For $58.19
      </td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">Video Card</td>
      <td class="pcpp-part-list-item"><a href="https://pcpartpicker.com/product/BJbkcf/evga-video-card-04gp41962kr">EVGA - GeForce GTX 960 4GB Superclocked Video Card</a></td>
      <td class="pcpp-part-list-price">
      </td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">Case</td>
      <td class="pcpp-part-list-item"><a href="https://pcpartpicker.com/product/XbKhP6/fractal-design-case-fdmcanode202aaus">Fractal Design - Node 202 HTPC Case w/450W Power Supply</a></td>
      <td class="pcpp-part-list-price">
        Purchased For $109.99
      </td>
    </tr>
    <tr>
      <td></td>
      <td class="pcpp-part-list-price-note">Prices include shipping, taxes, rebates, and discounts</td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td class="pcpp-part-list-total">Total</td>
      <td class="pcpp-part-list-total-price">$609.80</td>
    </tr>
    <tr>
      <td></td>
      <td class="pcpp-part-list-price-note">Generated by <a href="http://pcpartpicker.com">PCPartPicker</a> 2018-03-03 19:22 EST-0500</td>
      <td></td>
    </tr>
  </tbody>
</table>
                
            </div>
        </div>
        <?php include $_SERVER['DOCUMENT_ROOT'] . "/include/footer.html"; ?>
    </body>
</html>