<!DOCTYPE html>
<html>
    <head>
        <title>ID 97 - 98SeaTurtles Network</title>
        <link rel="stylesheet" href="/css/main.css">
		<?php include $_SERVER['DOCUMENT_ROOT'] . "/include/head.php"; ?>
    </head>
    <body>
        <?php
			include $_SERVER['DOCUMENT_ROOT'] . "/include/header.html";
            include $_SERVER['DOCUMENT_ROOT'] . "/include/menu.html";
        ?>
        <div id="content">
            <a href=".."><i>Back to My Computers</i></a>
            <div id="content-title">
                ID 97
            </div>
            <div id="content-subtitle">
                File Server (backups and general storage)
            </div>
            <div id="content-body">
                This is a deadicated file storage and backup server for my general use and and for my other servers to backup to
                <h3>Operating System</h3> FreeNAS<br>
                <h3>Parts List</h3>
                
                <a href="https://pcpartpicker.com/list/DbRP6s">PCPartPicker part list</a> / <a href="https://pcpartpicker.com/list/DbRP6s/by_merchant/">Price breakdown by merchant</a>
<table class="pcpp-part-list">
  <thead>
    <tr>
      <th>Type</th>
      <th>Item</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="pcpp-part-list-type">CPU</td>
      <td class="pcpp-part-list-item"><a href="https://pcpartpicker.com/product/WqVBD3/intel-celeron-g3930-29ghz-dual-core-processor-bx80677g3930">Intel - Celeron G3930 2.9GHz Dual-Core Processor</a></td>
      <td class="pcpp-part-list-price">
        Purchased For $37.49
      </td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">Motherboard</td>
      <td class="pcpp-part-list-item"><a href="https://pcpartpicker.com/product/QXdFf7/asrock-b250m-pro4-micro-atx-lga1151-motherboard-b250m-pro4">ASRock - B250M Pro4 Micro ATX LGA1151 Motherboard</a></td>
      <td class="pcpp-part-list-price">
        Purchased For $74.95
      </td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">Memory</td>
      <td class="pcpp-part-list-item"><a href="https://pcpartpicker.com/product/nD38TW/crucial-memory-ble8g4d26afea">Crucial - Ballistix Elite 8GB (1 x 8GB) DDR4-2666 Memory</a></td>
      <td class="pcpp-part-list-price">
        Purchased For $79.56
      </td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">Power Supply</td>
      <td class="pcpp-part-list-item"><a href="https://pcpartpicker.com/product/GQX2FT/evga-bt-450w-80-bronze-certified-atx-power-supply-100-bt-0450-k1">EVGA - BT 450W 80+ Bronze Certified ATX Power Supply</a></td>
      <td class="pcpp-part-list-price">
        Purchased For $23.86
      </td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">Other</td>
      <td class="pcpp-part-list-item"><a href="https://pcpartpicker.com/product/GHWrxr/rosewill-server-chassisserver-caserackmount-case-4u-metal-rack-mount-server-chassis-with-15-bays">Rosewill Server Chassis/Server Case/Rackmount Case, 4U Metal Rack Mount Server Chassis with 15 bays</a></td>
      <td class="pcpp-part-list-price">
        Purchased For $91.35
      </td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">Other</td>
      <td class="pcpp-part-list-item"><a href="https://pcpartpicker.com/product/nrp323/sandisk-16gb-ultra-flair-cz73-usb-30-flash-drive-speed-up-to-130mbs">SanDisk 16GB Ultra Flair CZ73 USB 3.0 Flash Drive, Speed Up to 130MB/s</a></td>
      <td class="pcpp-part-list-price">
        Purchased For $8.49
      </td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">Other</td>
      <td class="pcpp-part-list-item"><a href="https://pcpartpicker.com/product/J6Jkcf/hitachi-hgst-8tb-7200rpm-nas">Hitachi HGST 8TB 7200rpm NAS</a></td>
      <td class="pcpp-part-list-price">
        Purchased For $270.99
      </td>
    </tr>
    <tr>
      <td class="pcpp-part-list-type">Other</td>
      <td class="pcpp-part-list-item"><a href="https://pcpartpicker.com/product/J6Jkcf/hitachi-hgst-8tb-7200rpm-nas">Hitachi HGST 8TB 7200rpm NAS</a></td>
      <td class="pcpp-part-list-price">
        Purchased For $270.99
      </td>
    </tr>
    <tr>
      <td></td>
      <td class="pcpp-part-list-price-note">Prices include shipping, taxes, rebates, and discounts</td>
      <td></td>
    </tr>
    <tr>
      <td></td>
      <td class="pcpp-part-list-total">Total</td>
      <td class="pcpp-part-list-total-price">$857.68</td>
    </tr>
    <tr>
      <td></td>
      <td class="pcpp-part-list-price-note">Generated by <a href="http://pcpartpicker.com">PCPartPicker</a> 2018-03-03 19:08 EST-0500</td>
      <td></td>
    </tr>
  </tbody>
</table>
                
            </div>
        </div>
        <?php include $_SERVER['DOCUMENT_ROOT'] . "/include/footer.html";?>
    </body>
</html>